/* Generated By:JavaCC: Do not edit this line. CLIPSParserConstants.java */
using System;

namespace Creshendo.Util.Parser.Clips
{
    public struct CLIPSParserConstants_Fields
    {
        public const int AGGREGATE = 21;
        public const int ALLOWEDVALUES = 25;
        public const int AND1 = 94;
        public const int AND2 = 95;
        public const int ARROW = 75;
        public const int ASSERT = 22;
        public const int ASSERTTEMPORAL = 23;
        public const int ASSIGN = 76;
        public const int AUTOFOCUS = 24;
        public const int BIND = 15;
        public const int BIND2 = 16;
        public const int BIND3 = 17;
        public const int BIND4 = 18;
        public const int BINDING = 19;
        public const int BOOLEAN = 20;
        public const int CHAININGDIRECTION = 26;
        public const int COMMAND = 27;
        public const int COMMENT_TEXT = 7;
        public const int DECLARE = 28;
        public const int DEFAULT = 0;
        public const int DEFAULTVALUE = 40;
        public const int DEFCLASS = 29;
        public const int DEFFACT = 30;
        public const int DEFFUNCTION = 31;
        public const int DEFGENERIC = 32;
        public const int DEFGLOBAL = 33;
        public const int DEFINSTANCE = 34;
        public const int DEFMETHOD = 35;
        public const int DEFMODULE = 36;
        public const int DEFRULE = 37;
        public const int DEFTEMPLATE = 38;
        public const int DESCRIBECLASS = 39;
        public const int DIGIT = 101;
        public const int DIVIDE = 81;
        public const int DOUBLE = 41;
        public const int EFFECTIVE = 43;
        public const int END_COMMENT = 8;
        public const int EOF = 0;
        public const int EQ1 = 86;
        public const int EQ2 = 87;
        public const int EXISTS = 42;
        public const int EXPIRATION = 44;
        public const int EXPONENT = 13;
        public const int FACTINDEX = 45;
        public const int FALSE = 72;
        public const int FALSE2 = 73;
        public const int FLOAT = 46;
        public const int FLOATING_POINT_LITERAL = 12;
        public const int GE1 = 90;
        public const int GE2 = 91;
        public const int GT1 = 82;
        public const int GT2 = 83;
        public const int IDENTIFIER = 99;
        public const int IN_COMMENT = 1;
        public const int INTEGER = 47;
        public const int INTEGER_LITERAL = 11;
        public const int LBRACE = 9;
        public const int LE1 = 88;
        public const int LE2 = 89;
        public const int LETTER = 100;
        public const int LOGICAL = 48;
        public const int LONG = 49;
        public const int LT1 = 84;
        public const int LT2 = 85;
        public const int MINUS = 79;
        public const int MODIFY = 50;
        public const int MULTIPLY = 80;
        public const int MULTISLOT = 51;
        public const int NE1 = 92;
        public const int NE2 = 93;
        public const int NIL = 74;
        public const int NOAGENDA = 52;
        public const int NOLOOP = 53;
        public const int NOTCE = 55;
        public const int NUMBER = 54;
        public const int OR1 = 96;
        public const int OR2 = 97;
        public const int PATH_LITERAL = 102;
        public const int PLUS = 78;
        public const int RBRACE = 10;
        public const int RELATIVETIME = 59;
        public const int REMEMBERMATCH = 56;
        public const int RETRACT = 57;
        public const int RULEVERSION = 58;
        public const int SALIENCE = 60;
        public const int SEMICOLON = 77;
        public const int SEND = 61;
        public const int SHORT = 62;
        public const int SLOT = 63;
        public const int STRING = 64;
        public const int STRING_LITERAL = 14;
        public const int SYMBOL = 65;
        public const int TEMPORAL = 67;
        public const int TEMPORALACTIVATION = 66;
        public const int TEST = 68;
        public const int TILDA = 98;
        public const int TRUE = 69;
        public const int TRUE2 = 70;
        public const int TYPEDEF = 71;
        public static readonly String[] tokenImage = new String[] {"<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\";;\"", "<token of kind 6>", "<COMMENT_TEXT>", "<END_COMMENT>", "\"(\"", "\")\"", "<INTEGER_LITERAL>", "<FLOATING_POINT_LITERAL>", "<EXPONENT>", "<STRING_LITERAL>", "<BIND>", "<BIND2>", "<BIND3>", "<BIND4>", "\"bind\"", "\"BOOLEAN\"", "\"aggregate\"", "\"assert\"", "\"assert-temporal\"", "\"auto-focus\"", "\"allowed-values\"", "\"chaining-direction\"", "\"command\"", "\"declare\"", "\"defclass\"", "\"deffact\"", "\"deffunction\"", "\"defgeneric\"", "\"defglobal\"", "\"definstance\"", "\"defmethod\"", "\"defmodule\"", "\"defrule\"", "\"deftemplate\"", "\"describe-class\"", "\"default\"", "\"DOUBLE\"", "\"exists\"", "\"effective-date\"", "\"expiration-date\"", "\"fact-index\"", "\"FLOAT\"", "\"INTEGER\"", "\"logical\"", "\"LONG\"", "\"modify\"", "\"multislot\"", "\"no-agenda\"", "\"no-loop\"", "\"NUMBER\"", "\"not\"", "\"remember-match\"", "\"retract\"", "\"rule-version\"", "\"relative-time\"", "\"salience\"", "\"send\"", "\"SHORT\"", "\"slot\"", "\"STRING\"", "\"symbol\"", "\"temporal-activation\"", "\"temporal\"", "\"test\"", "\"TRUE\"", "\"true\"", "\"type\"", "\"FALSE\"", "\"false\"", "\"nil\"", "\"=>\"", "\"<-\"", "\";\"", "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\">\"", "\"gt\"", "\"<\"", "\"lt\"", "\"==\"", "\"eq\"", "\"<=\"", "\"le\"", "\">=\"", "\"ge\"", "\"!=\"", "\"ne\"", "\"and\"", "\"&\"", "\"or\"", "\"|\"", "\"~\"", "<IDENTIFIER>", "<LETTER>", "<DIGIT>", "<PATH_LITERAL>"};
    }

    public interface CLIPSParserConstants
    {
        //UPGRADE_NOTE: Members of interface 'CLIPSParserConstants' were extracted into structure 'CLIPSParserConstants_Fields'. 'ms-help://MS.VSCC.2003/commoner/redir/redirect.htm?keyword="jlca1045"'
    }
}