(deffunction test-something ()
  ;; ----------------------------------------------------------------------
  (printout t ">>> evenp" crlf)
  (printout t (not (evenp 1)) " ")
  (printout t (not (evenp 1.)) " ")
  (printout t (evenp 2.) " ")
  (printout t (evenp 2) " ")
  (printout t (evenp 0) " ")
  (printout t (evenp 0.) " ")
  (printout t (not (evenp -1)) " ")
  (printout t (evenp -2) crlf)
  ;; ----------------------------------------------------------------------
  (printout t ">>> oddp" crlf)
  (printout t (oddp 1) " ")
  (printout t (oddp 1.) " ")
  (printout t (not (oddp 2.)) " ")
  (printout t (not (oddp 2)) " ")
  (printout t (not (oddp 0)) " ")
  (printout t (not (oddp 0.)) " ")
  (printout t (oddp -1) " ")
  (printout t (not (oddp -2)) crlf)
  ;; ----------------------------------------------------------------------
  (printout t ">>> numberp" crlf)
  (printout t (not (numberp a)) " ")
  (printout t (not (numberp "a")) " ")
  (printout t (numberp 1.0) " ")
  (printout t (numberp 1) " ")
  (printout t (numberp (long "123")) crlf)
  ;; ----------------------------------------------------------------------
  (printout t ">>> floatp" crlf)
  (printout t (not (floatp 1)) " ")
  (printout t (floatp 1.0) " ")
  (printout t (floatp 1.1) " ")
  (printout t (floatp 0.) crlf)
  ;; ----------------------------------------------------------------------
  (printout t ">>> integerp" crlf)
  (printout t (not (integerp 1.0)) " ")
  (printout t (integerp 1) " ")
  (printout t (integerp 0) crlf)
  ;; ----------------------------------------------------------------------
  (printout t ">>> longp" crlf)
  (printout t (not (longp a)) " ")
  (printout t (not (longp "a")) " ")
  (printout t (longp (long "123")) " " crlf)
  ;;comment out for now
  ;;(printout t (longp (call System currentTimeMillis)) crlf)
  ;; ----------------------------------------------------------------------
  (printout t ">>> lexemep" crlf)
  (printout t (not (lexemep 1.0)) " ")
  (printout t (not (lexemep 1)) " ")
  (printout t (not (lexemep (create$ a))) " ")
  (printout t (lexemep a) " ")
  (printout t (lexemep "a") crlf)
  ;; ----------------------------------------------------------------------
  (printout t ">>> symbolp" crlf)
  (printout t (not (symbolp 1.0)) " ")
  (printout t (not (symbolp 1)) " ")
  (printout t (not (symbolp "a")) " ")
  (printout t (symbolp a) crlf)
  ;; ----------------------------------------------------------------------
  (printout t ">>> stringp" crlf)
  (printout t (not (stringp 1.0)) " ")
  (printout t (not (stringp 1)) " ")
  (printout t (not (stringp a)) " ")
  (printout t (stringp "a") crlf)
  ;; ----------------------------------------------------------------------
  (printout t ">>> external-addressp" crlf)
  (bind ?o (new System.Object))
  (printout t (external-addressp ?o) " ")
  (printout t (not (external-addressp 1)) " ")
  (printout t (not (external-addressp "Hello")) crlf)
)


(printout t "Testing predicates:" crlf)
(test-something)
(printout t "Test done." crlf)
(exit)  